### ISSUE TITLE
Why need a store

### ISSUE THREAD

**Issue by anton-johansson** [whizzosoftware/WZWave#19]
What's the purpose of the `store`? It's necessary to have one, or the controller won't start. What is it actually storing?

If I would move my application (with lots of devices in use) to another server and lose my store, what would that mean, in practice?

**Comment by whizzosoftware** [comment]
The store is useful for two reasons: 1) Initial interrogation of Z-Wave devices is an expensive operation -- WZWave stores device metadata so it doesn't have to re-interrogate when the library is restarted. 2) Devices that can sleep (e.g. battery-powered devices) may be offline and won't respond to interrogation requests. In that case, meta-data from the store would be the only way to get any information about the device at library startup time.

**Comment by whizzosoftware** [comment]
FYI, there is a forum for WZWave available here: https://community.hobson-automation.com/ It might be a better place to have discussions like this. That would keep the issue tracker strictly for items that are identified as needing work.

**Comment by anton-johansson** [comment]
Allright, thanks for the summary! I guess I'll need to implement my own `PersistentStore` against my database to keep it portable. :)

You're right. I'll keep discussions & questions in the forums in the future, thanks for the pointer!
